/**
 * Build the folder to upload to HostGator.
 *
 *   npm run package
 *
 * There is no build step in this project - the browser runs the source as-is.
 * This just copies the RUNTIME files into dist/ so nobody has to remember which
 * ones those are, and writes an .htaccess suited to Apache shared hosting.
 *
 * Deliberately NOT copied: tests, scripts, the workbook, package.json, the
 * README. None of it is needed to serve the site, and the workbook holds Unit
 * Cost, which must never sit in a public web root.
 */

import { cp, mkdir, rm, writeFile, readdir, stat } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = join(ROOT, 'dist');

/** Everything the page actually loads, and nothing else. */
const INCLUDE = [
  'index.html',
  'config.js',      // the published-CSV URLs; no secrets, safe to publish
  'assets',
  'src',
  'data',           // the offline fallback snapshot
];

/**
 * Apache config for shared hosting.
 *
 * The caching rules are the important part. Twice during development a change
 * looked like it had not deployed when the browser was simply holding an old
 * copy of a module, so the code and data are served no-cache and only the
 * logo is allowed to sit in cache.
 */
const HTACCESS = `# SRR Gutter Estimator - Apache config for HostGator shared hosting.
# Generated by scripts/package.mjs. Edit there, not here.

# --- force HTTPS ---------------------------------------------------------
# The clipboard button needs a secure context, and an estimate form asking for
# an address has no business being served over plain HTTP.
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP:X-Forwarded-Proto} !https
  RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [R=301,L]
</IfModule>

# --- correct types -------------------------------------------------------
<IfModule mod_mime.c>
  AddType text/javascript .js
  AddType text/css .css
  AddType text/csv .csv
  AddType image/svg+xml .svg
</IfModule>

# --- caching -------------------------------------------------------------
# The site has no build step and no filename hashing, so a cached module is a
# stale module with no way to bust it. Code and pricing revalidate every time;
# only images are allowed to linger.
<IfModule mod_headers.c>
  <FilesMatch "\\.(html|js|css|csv)$">
    Header set Cache-Control "no-cache, must-revalidate"
  </FilesMatch>
  <FilesMatch "\\.(png|jpg|jpeg|gif|svg|ico|woff2?)$">
    Header set Cache-Control "public, max-age=604800"
  </FilesMatch>
</IfModule>

<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/css text/javascript text/csv application/javascript
</IfModule>

# --- tidy ----------------------------------------------------------------
# The deploy workflow's sync-state file lists every file it uploaded. Harmless,
# but there is no reason to serve it.
<Files ".ftp-deploy-sync-state.json">
  Require all denied
</Files>
Options -Indexes
DirectoryIndex index.html
`;

async function walk(dir, base = dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...await walk(full, base));
    else out.push(relative(base, full).replace(/\\/g, '/'));
  }
  return out;
}

async function main() {
  await rm(DIST, { recursive: true, force: true });
  await mkdir(DIST, { recursive: true });

  for (const item of INCLUDE) {
    await cp(join(ROOT, item), join(DIST, item), { recursive: true });
  }
  await writeFile(join(DIST, '.htaccess'), HTACCESS, 'utf8');

  const files = await walk(DIST);
  let bytes = 0;
  for (const f of files) bytes += (await stat(join(DIST, f))).size;

  // A last look for anything that should never reach a public web root.
  const leaked = files.filter((f) => /\.xlsx$/i.test(f) || /^(tests|scripts|node_modules)\//.test(f));
  if (leaked.length) {
    console.error('REFUSING TO PACKAGE - these must not be published:');
    for (const f of leaked) console.error('  ' + f);
    process.exit(1);
  }

  console.log(`dist/  ${files.length} files, ${Math.round(bytes / 1024)} KB\n`);
  for (const f of files.sort()) console.log('  ' + f);
  console.log('\nUpload the CONTENTS of dist/ into public_html on HostGator.');
  console.log('Include the .htaccess - File Manager hides dotfiles until you');
  console.log('turn on "Show Hidden Files" in its settings.');
}

main().catch((err) => {
  console.error('Packaging failed:', err.message);
  process.exit(1);
});
